# Generated by Django 2.2.2 on 2019-06-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190614_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ator',
            options={'verbose_name_plural': 'Atores'},
        ),
        migrations.AlterModelOptions(
            name='atuoufilme',
            options={'verbose_name_plural': 'Atuaram no filmes'},
        ),
        migrations.AlterModelOptions(
            name='diretor',
            options={'verbose_name_plural': 'Diretores'},
        ),
        migrations.AlterModelOptions(
            name='dirigiufilme',
            options={'verbose_name_plural': 'Dirigiram os filmes'},
        ),
        migrations.AlterModelOptions(
            name='filmepremiado',
            options={'verbose_name_plural': 'Filmes premiados'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='premioatuacao',
            options={'verbose_name_plural': 'Prêmios cedidos para atuações'},
        ),
        migrations.AlterModelOptions(
            name='premioatuacaofilme',
            options={'verbose_name_plural': 'Prêmios pela atuações'},
        ),
        migrations.AlterModelOptions(
            name='premiodirecao',
            options={'verbose_name_plural': 'Prêmios ceditos pela direção'},
        ),
        migrations.AlterModelOptions(
            name='premiodirecaofilme',
            options={'verbose_name_plural': 'Prêmios pelas direções'},
        ),
        migrations.AlterModelOptions(
            name='premiofilme',
            options={'verbose_name_plural': 'Prêmios cedidos aos filmes'},
        ),
        migrations.AddField(
            model_name='filme',
            name='nome_original',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Nome Original do Filme'),
        ),
        migrations.AlterField(
            model_name='premioatuacaofilme',
            name='ano_premio',
            field=models.IntegerField(verbose_name='Ano da premiação'),
        ),
    ]
