# Generated by Django 2.2.2 on 2019-06-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190617_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ('sobrenome',)},
        ),
        migrations.AlterModelOptions(
            name='ator',
            options={'ordering': ('artista',), 'verbose_name_plural': 'Atores'},
        ),
        migrations.AlterModelOptions(
            name='atuoufilme',
            options={'ordering': ('ator', 'filme'), 'verbose_name_plural': 'Atuaram no filmes'},
        ),
        migrations.AlterModelOptions(
            name='diretor',
            options={'ordering': ('artista',), 'verbose_name_plural': 'Diretores'},
        ),
        migrations.AlterModelOptions(
            name='dirigiufilme',
            options={'ordering': ('diretor', 'filme'), 'verbose_name_plural': 'Dirigiram os filmes'},
        ),
        migrations.AlterModelOptions(
            name='filme',
            options={'ordering': ('nome_filme', 'ano_lancamento')},
        ),
        migrations.AlterModelOptions(
            name='filmepremiado',
            options={'ordering': ('ano_premiacao', 'premio', 'filme'), 'verbose_name_plural': 'Filmes premiados'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ('genero',), 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ('nome_pais',), 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='premioatuacao',
            options={'ordering': ('nome_premio',), 'verbose_name_plural': 'Prêmios cedidos para atuações'},
        ),
        migrations.AlterModelOptions(
            name='premioatuacaofilme',
            options={'ordering': ('ano_premio', 'premio_atuacao', 'atuacao'), 'verbose_name_plural': 'Prêmios pela atuações'},
        ),
        migrations.AlterModelOptions(
            name='premiodirecao',
            options={'ordering': ('nome_premio',), 'verbose_name_plural': 'Prêmios ceditos pela direção'},
        ),
        migrations.AlterModelOptions(
            name='premiodirecaofilme',
            options={'ordering': ('ano_premio', 'premio_direcao', 'direcao'), 'verbose_name_plural': 'Prêmios pelas direções'},
        ),
        migrations.AlterModelOptions(
            name='premiofilme',
            options={'ordering': ('nome_premio',), 'verbose_name_plural': 'Prêmios cedidos aos filmes'},
        ),
        migrations.RenameField(
            model_name='premioatuacaofilme',
            old_name='atauacao',
            new_name='atuacao',
        ),
    ]
