# Generated by Django 2.2.2 on 2019-06-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190617_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atuoufilme',
            options={'ordering': ('filme', 'ator'), 'verbose_name_plural': 'Atuaram no filmes'},
        ),
        migrations.AlterModelOptions(
            name='dirigiufilme',
            options={'ordering': ('filme', 'diretor'), 'verbose_name_plural': 'Dirigiram os filmes'},
        ),
        migrations.AddField(
            model_name='filme',
            name='classificacao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Classificação etária'),
        ),
        migrations.AddField(
            model_name='filme',
            name='metragem',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (min)'),
        ),
    ]
