# Generated by Django 2.2.2 on 2019-06-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190617_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='classificacao',
            field=models.CharField(default='Livre', max_length=10, verbose_name='Classificação etária'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='metragem',
            field=models.PositiveIntegerField(default=120, verbose_name='Duração (min)'),
        ),
    ]
